# Generated by Django 6.0.3 on 2026-04-21 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=100)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='estimated_days',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='transporterinfo',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='transporterinfo',
            name='service_areas',
        ),
        migrations.RemoveField(
            model_name='transporterinfo',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='delivery',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='size_acres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='transporterinfo',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='transporter',
            field=models.ForeignKey(blank=True, limit_choices_to={'userprofile__user_type': 'transporter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'userprofile__user_type': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'userprofile__user_type': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('ton', 'Ton'), ('piece', 'Piece')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='transporterinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('transporter', 'Transporter'), ('admin', 'Admin')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
