# Generated by Django 6.0.3 on 2026-04-21 15:29

import django.db.models.deletion
from django.db import migrations, models


def seed_categories_and_backfill_products(apps, schema_editor):
    Product = apps.get_model('marketplace', 'Product')
    ProductCategory = apps.get_model('marketplace', 'ProductCategory')

    starter_categories = [
        'Potato',
        'Tomato',
        'Onion',
        'Carrot',
        'Cabbage',
        'Lettuce',
        'Spinach',
        'Zucchini',
        'Eggplant',
        'Bell Pepper',
        'Cucumber',
        'Garlic',
        'Pumpkin',
        'Turnip',
        'Pea',
    ]

    for name in starter_categories:
        ProductCategory.objects.get_or_create(name=name, defaults={'is_active': True})

    for product in Product.objects.all():
        category, _ = ProductCategory.objects.get_or_create(
            name=product.name,
            defaults={'is_active': True},
        )
        product.category = category
        product.save(update_fields=['category'])


def remove_seeded_categories(apps, schema_editor):
    ProductCategory = apps.get_model('marketplace', 'ProductCategory')
    Product = apps.get_model('marketplace', 'Product')
    Product.objects.update(category=None)
    ProductCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='marketplace.productcategory'),
        ),
        migrations.RunPython(seed_categories_and_backfill_products, remove_seeded_categories),
    ]
