# Generated by Django 6.0.3 on 2026-04-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_productcategory_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='size_acres',
        ),
        migrations.AddField(
            model_name='farm',
            name='area_hectares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Area (hectares)'),
        ),
        migrations.AddField(
            model_name='farm',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
