# Generated by Django 6.0.3 on 2026-05-04 19:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_product_description_product_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
