# Generated by Django 6.0.3 on 2026-05-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_delivery_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='farm',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='farm',
            name='wilaya',
            field=models.CharField(blank=True, choices=[('Adrar', 'Adrar'), ('Chlef', 'Chlef'), ('Laghouat', 'Laghouat'), ('Oum El Bouaghi', 'Oum El Bouaghi'), ('Batna', 'Batna'), ('Béjaïa', 'Béjaïa'), ('Biskra', 'Biskra'), ('Béchar', 'Béchar'), ('Blida', 'Blida'), ('Bouira', 'Bouira'), ('Tamanrasset', 'Tamanrasset'), ('Tébessa', 'Tébessa'), ('Tlemcen', 'Tlemcen'), ('Tiaret', 'Tiaret'), ('Tizi Ouzou', 'Tizi Ouzou'), ('Alger', 'Alger'), ('Djelfa', 'Djelfa'), ('Jijel', 'Jijel'), ('Sétif', 'Sétif'), ('Saïda', 'Saïda'), ('Skikda', 'Skikda'), ('Sidi Bel Abbès', 'Sidi Bel Abbès'), ('Annaba', 'Annaba'), ('Guelma', 'Guelma'), ('Constantine', 'Constantine'), ('Médéa', 'Médéa'), ('Mostaganem', 'Mostaganem'), ("M'Sila", "M'Sila"), ('Mascara', 'Mascara'), ('Ouargla', 'Ouargla'), ('Oran', 'Oran'), ('El Bayadh', 'El Bayadh'), ('Illizi', 'Illizi'), ('Bordj Bou Arréridj', 'Bordj Bou Arréridj'), ('Boumerdès', 'Boumerdès'), ('El Tarf', 'El Tarf'), ('Tindouf', 'Tindouf'), ('Tissemsilt', 'Tissemsilt'), ('El Oued', 'El Oued'), ('Khenchela', 'Khenchela'), ('Souk Ahras', 'Souk Ahras'), ('Tipaza', 'Tipaza'), ('Mila', 'Mila'), ('Aïn Defla', 'Aïn Defla'), ('Naâma', 'Naâma'), ('Aïn Témouchent', 'Aïn Témouchent'), ('Ghardaïa', 'Ghardaïa'), ('Relizane', 'Relizane')], max_length=50),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
