# Generated by Django 6.0.3 on 2026-05-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
